[project]
name = "chapter2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.14.3",
    "tiktoken==0.8.0",
    "torch>=2.9.0",
]
